### ISSUE TITLE
using this script ,my ida crashed.

### ISSUE THREAD

**Issue by xiaohang99** [Cr4sh/IDA-VMware-GDB#1]
my ida version is 6.8 64bit,when I try this script ,ida crashed.
debug this script, found crash place :
RunPlugin("pdb", 3) # use 1 to get a confirmation prompt

I fix param 3 to 1 ,crashed fixed,what cause this crash ?

**Comment by Cr4sh** [comment]
Version issue with IDA or Windows debug libs.
